wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.39.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1728393806.0
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 103
      2:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 103
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.10.11
      5: 0.16.5
      6: 4.39.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
